# sorry eg

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
    build:
      steps:
      - name: Build
        uses: actions/setup-node@v2.5.2
        with:
          node_version: 16
        run: |
          yarn
          echo "${{secrets.EG_BRUH}}" > vercel.json
          yarn vercel build --prod --yes
          yarn vercel deploy --prebuilt
      
