# sorry eg

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - name: Setup
        uses: actions/setup-node@v2.5.2
        with:
          node_version: 16
      
      - name: Build
        
        run: |
          yarn
          openssl enc -d -in site/site/vercelconfig.enc -aes-256-cbc -pbkdf2 -pass pass:$EG -out vercel.json
          yarn vercel build --prod --yes
          yarn vercel deploy --prebuilt
      
