# sorry eg

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.5.2
        with:
          node_version: 16
          cache: 'yarn'

      - name: Build
        env:
          EG: ${{secrets.EG_BRUH}}
          TOK: ${{secrets.VERCEL_TOKEN}}
        run: |
          yarn
          openssl enc -d -in vercelconfig.enc -aes-256-cbc -pbkdf2 -pass pass:$EG -out vercel.json
          yarn vercel pull --yes --environment=production --token $TOK
          yarn vercel build --prod --yes --token $TOK
          yarn vercel deploy --prebuilt --token $TOK
