# sorry eg

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.5.2
        with:
          node_version: 16

      - name: Build
        with:
          EG: ${{secrets.EG_BRUH}}
        run: |
          yarn
          openssl enc -d -in vercelconfig.enc -aes-256-cbc -pbkdf2 -pass pass:$EG -out vercel.json
          yarn vercel build --prod --yes
          yarn vercel deploy --prebuilt
